# Generated by Django 3.2.7 on 2021-09-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinaton',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
